config/routes.rb
Rails.application.routes.draw do
	resources :categories do
		resources :products, only: [:create, :destroy]
	end


	root 'categories#index'
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  validates :name, :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_category, only: [:show, :edit, :update, :destroy]

	# GET /categories
	# GET /categories.json
	def index
		@categories = Category.all
	end

	# GET /categories/1
	# GET /categories/1.json
	def show
		@product = Product.new

		# esto es para mostrarlo en la vista show
		@product_All = @category.products.order(updated_at: :desc)

	end

	# GET /categories/new
	def new
		@category = Category.new
	end

	# GET /categories/1/edit
	def edit
	end

	# POST /categories
	# POST /categories.json
	def create
		@category = Category.new(category_params)

		respond_to do |format|
			if @category.save
				format.html { redirect_to @category, notice: 'Categoría fue creada Satisfactoriamente!!.' }
				format.json { render :show, status: :created, location: @category }
			else
				format.html { render :new }
				format.json { render json: @category.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /categories/1
	# PATCH/PUT /categories/1.json
	def update
		respond_to do |format|
			if @category.update(category_params)
				format.html { redirect_to @category, notice: 'Categoría fue actuañizada!!.' }
				format.json { render :show, status: :ok, location: @category }
			else
				format.html { render :edit }
				format.json { render json: @category.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /categories/1
	# DELETE /categories/1.json
	def destroy
		@category.destroy
		respond_to do |format|
			format.html { redirect_to categories_url, notice: 'Categoría fue eliminada.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_category
			@category = Category.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def category_params
			params.require(:category).permit(:name)
		end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_category, only: [:create, :destroy]

	def create
		@product = Product.new(product_params)		
		@product.category = @category
		@product.save
		
		redirect_to @category
	end

	def destroy
		producto = Product.find(params[:id])
		producto.destroy
		
		redirect_to @category
	end
	
	private
	def product_params
		params.require(:product).permit(:name, :price)
	end

	def set_category
		@category = Category.find(params[:category_id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
	<% if category.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

			<ul>
			<% category.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>


	<div class="field">
		<%= form.label 'Nombre:' %>
		<%= form.text_field :name, id: :category_name, autofocus: true %>
	</div>


	<div class="actions"><br>
		<%= form.submit 'Guardar', class:'btn btn-primary' %>
	</div>
<% end %>

app/views/categories/edit.html.erb
<div class="col-md-10 col-xs-12 col-sm-11">
	<div class="card bg-light">
		
		<h1 class="text-center"> Edición de Categoría</h1>
		
		<%= render 'form', category: @category %>
		
		<div>
			<%= link_to 'Mostrar', @category, class:'btn btn-info' %>
			<%= link_to 'Volver', categories_path, class:'btn btn-secondary' %>
		</div>

	</div>
</div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Categorías</h1>

<div class="table-responsive">
	<table class="table table-striped table-hover ">
		<thead>
			<tr class="table-success">
				<th>Name</th>
				<th>Cantidad de Productos</th>
				<th colspan="3"></th>
			</tr>
		</thead>
		
		<tbody>
			<% @categories.each do |category| %>
			<tr>
				<td><%= link_to category.name, category %></td>
				<td><%= category.products.count %></td>
				<td><%= link_to 'Editar', edit_category_path(category), class:'btn btn-warning' %>
				<%= link_to 'Eliminar', category, method: :delete, data: { confirm: 'Está Seguro?' }, class:'btn btn-danger' %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

<br>

<%= link_to 'Nueva Categoría', new_category_path, class:'btn btn-primary' %>

app/views/categories/new.html.erb
<div class="col-md-10 col-xs-12 col-sm-11">
	<div class="card bg-light">
		<h1 class="text-center">Nueva Categoría</h1>
		
		<%= render 'form', category: @category %>
		
		<div>
			<%= link_to 'Volver', categories_path, class:'btn btn-secondary' %>
		</div>

	</div>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card bg-light large-padding text-center" style="width: 30rem;">
	<h3><strong>Nombre:</strong>
		<%= @category.name %>
	</h3>
	
	<div class="form-group input-group">
		<%= form_with(model:[@category, @product]) do |f| %>
		<label class="has-float-label">
			<%= f.text_field :name, autofocus: true, class:'form-control', placeholder:'nombre'  %>
			<span>Nombre</span>
		</label>
		
		<br>
		<label class="has-float-label">
			<%= f.number_field :price, class:'form-control', placeholder:'precio' %>
			<span>Precio</span>
		</label>
		
		<br>
		<%= f.submit 'Guardar', class:'btn btn-primary' %>
		<% end %>
	</div>
</div><br>

<div class="row">
	<div class="col-lg-6 col-md-8 col-xs-5">
		<table class="table table-striped">
			<thead>
				<tr>
					<th scope="col">Nombre</th>
					<th scope="col">Precio</th>
					<th colspan="1"></th>
				</tr>
			</thead>
			<tbody>
				<% @product_All.each do |product| %>
				<tr>
					<td>		<%= product.name %></td>
					<td> <%= product.price %> </td>
					<td><%= link_to "Eliminar", category_product_path(@category, product), method: :delete, class:'btn btn-danger' %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>





<%= link_to 'Editar', edit_category_path(@category), class:'btn btn-warning' %>
<%= link_to 'Volver', categories_path, class:'btn btn-secondary' %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #73a365;">
	<a class="navbar-brand" href= <%= root_path %> >HOME</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item active">
				<a class="nav-link" href= <%= new_category_path %> > Crear Categoria <span class="sr-only">(current)</span></a>
			</li>
		</ul>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Tallercrud01</title>
	<%= csrf_meta_tags %>

	<link rel="stylesheet" href="https://cdn.rawgit.com/tonystar/bootstrap-float-label/v4.0.2/bootstrap-float-label.min.css"/>
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	
	<header>
		<%= render 'layouts/navbar' %>
	</header>
	
	
	<%= yield %>
	
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>